### ISSUE TITLE
Comparison with iNeRF

### ISSUE THREAD

**Issue by kwea123** [ueda0319/neddf#53]
I think iNeRF is the most similar work with yours, but I didn't see any comparison in the paper. Is there any reason why you didn't do it? The localization is the main contribution if I understand correctly.

**Comment by ueda0319** [comment]
Thank you for your question.
The "photometric error" results in the paper correspond to the application of the iNeRF optimization flow to NeDDF, as shown on page 8.
That is to ensure equality of experimental conditions. In practice, there is no significant difference in the optimization results with the photometric error between NeRF and NeDDF, so we listed the NeDDF results.

**Comment by kwea123** [comment]
Thank you!
